# STARSHIP PROMPT -- https://starship.rs/

command_timeout = 1500

[aws]
symbol = "îŒ½  "
format = '[$symbol($profile)(\($region\))($duration)]($style) '

[[battery.display]]
threshold = 15

[[battery.display]]
threshold = 30
style = "bold yellow"

[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"
vicmd_symbol = "[V](bold green)"

[cmake]
format = '[$symbol]($style) '

[cmd_duration]
disabled = true

[conda]
symbol = "ï„Œ "
format = '[$symbol$environment]($style) '

[crystal]
format = '[$symbol]($style) '

[dart]
symbol = "î˜ "
format = '[$symbol]($style) '

[deno]
format = '[$symbol]($style) '

[directory]
read_only = " ï ½"

[docker_context]
symbol = "ïŒˆ "
format = '[$symbol$context]($style) '

[dotnet]
format = '[$symbol(ğŸ¯ $tfm)]($style) '

[elixir]
symbol = "î‰µ "
format = '[$symbol($version \(OTP $otp_version\))]($style) '

[elm]
symbol = "î˜¬ "
format = '[$symbol]($style) '

[erlang]
format = '[$symbol]($style) '

[gcloud]
format = '[$symbol$account(@$domain)(\($region\))]($style) '

[git_branch]
symbol = "ï˜ "
format = '[$symbol$branch]($style)'

[git_status]
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
style = "yellow"
format = '([$all_status$ahead_behind]($style)) '

[golang]
symbol = "î˜§ "
style = "bold blue"
format = '[$symbol]($style) '

[helm]
format = '[$symbol]($style) '

[hg_branch]
symbol = "ï˜ "
format = '[$symbol$branch]($style) '

[java]
symbol = "î‰– "
format = '[$symbol]($style) '

[julia]
symbol = "î˜¤ "
format = '[$symbol]($style) '

[kotlin]
format = '[$symbol]($style) '

[kubernetes]
format = '[$symbol$context( \($namespace\))]($style) '

[lua]
format = '[$symbol]($style) '

[memory_usage]
symbol = "ï¡š "
format = '$symbol[$ram( | $swap)]($style) '

[nim]
symbol = "ïš¤ "
format = '[$symbol]($style) '

[nix_shell]
symbol = "ï‹œ "
format = '[$symbol$state( \($name\))]($style) '

[nodejs]
format = '[$symbol]($style) '

[ocaml]
format = '[$symbol(\($switch_indicator$switch_name\))]($style) '

[openstack]
format = '[$symbol$cloud(\($project\))]($style) '

[package]
symbol = "ï£– "
format = '[$symbol$version]($style) '

[perl]
symbol = "î© "
format = '[$symbol]($style) '

[php]
symbol = "î˜ˆ "
format = '[$symbol]($style) '

[purescript]
format = '[$symbol]($style) '

[python]
symbol = "î˜† "
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '

[red]
format = '[$symbol]($style) '

[ruby]
symbol = "îˆ¾ "
format = '[$symbol]($style) '

[rust]
symbol = "î¨ "
format = '[$symbol]($style) '

[scala]
symbol = "îœ· "
format = '[$symbol]($style) '

[shell]
fish_indicator = "ïœ¹"
powershell_indicator = "ï‘ _"
bash_indicator = "âŒ¯"
zsh_indicator = "âƒ"
unknown_indicator = "?"
disabled = false

[shlvl]
symbol = "ï„  "

[swift]
symbol = "ï¯£ "
format = '[$symbol]($style) '

[terraform]
format = '[$symbol$workspace]($style) '

[time]
format = '[$time]($style) '

[username]
format = '[$user]($style) '

[vagrant]
format = '[$symbol]($style) '

[vlang]
format = '[$symbol]($style) '

[zig]
format = '[$symbol]($style) '
